<table>
 <tr align=left><td><img align=left src="./images/CC-BY.png">
 <td>Text provided under a Creative Commons Attribution license, CC-BY. All code is made available under the FSF-approved MIT license. (c) Kyle T. Mandli</td>
</table>

# Introduction to NumPy

NumPy is the basic library in Python that defines a number of essential data structures and routines for doing numerical computing (among other things).  Many of the semantics for manipulating the most basic data structure, the `ndarray`, are identical to manipulating `list`s with a few key exceptions.  We will cover those and some of the other important points when working with NumPy.

Topics:
 - The `ndarray`
 - Mathematical functions
 - Array manipulations
 - Common array functions

## `ndarray`

The `ndarray` forms the most basic type of data-structure for NumPy.  As the name suggests the `ndarray` is an array that can have as many dimensions as you specify.  For matlab users this should be familiar although note that the `ndarray` does not exactly behave as you might expect the same object to in matlab.  Here are some examples usages:

In [1]:
import numpy

Define a 2x2 array, note that unlike MATLAB we need commas everywhere:

In [2]:
my_array = numpy.array([[1, 2], [3, 4]])
print my_array

[[1 2]
 [3 4]]


Get the `(0, 1)` component of the array:

In [3]:
my_array[0, 1]

2

Fetch the first column of the matrix:

In [4]:
my_array[:,0]

array([1, 3])

Define a column vector:

In [6]:
my_vec = numpy.array([[1], [2]])
print my_vec

[[1]
 [2]]


Multiply `my_array` by the vector `my_vec` in the usual linear algebra sense (equivalent to MATLAB's `*`)

In [8]:
numpy.dot(my_array, my_vec)
numpy.cross?

Multiply `my_array` and `my_vec` by "broadcasting" the matching dimensions, equivalent to MATLAB's `.*` form:

In [9]:
my_array * my_vec

array([[1, 2],
       [6, 8]])

## Common Array Constructors
Along with the must common constructor for `ndarray`s above (`array`) there are number of other ways to create arrays with particular values inserted in them.  Here are a few that can be useful.

The `linspace` command (similar to MATLAB's `linspace` command) take three arguments, the first define a range of values and the third how many points to put in between them.  This is great if you want to evaluate a function at evently space points between two numbers.

In [11]:
numpy.linspace(-1, 1, 10)
numpy.linspace?

Another useful set of functions are `zeros` and `ones` which create an array of zeros and ones respectively (again equivalent to the functions in MATLAB).

In [12]:
numpy.zeros([3, 3])

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [15]:
numpy.ones([2, 3, 2])

array([[[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]],

       [[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]]])

Note that NumPy arrays can be reshaped and expanded after they are created but this can be computational expense and may be difficult to fully understand the consequences of (`reshape` in particular can be difficult).  One way to avoid these issues is to create an empty array of the right size and storing the calculated values as you find them.  The array constructor to do this is called `empty`:

In [16]:
numpy.empty([2,3])

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

Note that here the IPython notebook is displaying zeros (or something close to this).  The values are almost always not zero but the display of values is truncated to help with displaying long numbers.  This can be controlled via the settings `` TODO!

## Array Manipulations
Sometimes, despite our best efforts, we will need to manipulate the size or shape of our already created arrays.
 - Note that these functions can be complex to use and can be computationally expensive so use sparingly!
 - That being said, often these can still be a great way to avoid using too much memory and still may be faster than creating multiple arrays.
 - Check out the [NumPy Docs](http://docs.scipy.org/doc/numpy/reference/routines.array-manipulation.html) for more functions beyond these basic ones

One of the important aspects of an array is its `shape`.

In [17]:
A = numpy.array([[1, 2, 3], [4, 5, 6]])
print "A Shape = ", A.shape
print A

A Shape =  (2, 3)
[[1 2 3]
 [4 5 6]]


We can reshape an array.

In [24]:
B = A.reshape((6,1))
print "A Shape = ", A.shape
print "B Shape = ", B.shape
print B

A Shape =  (2, 3)
B Shape =  (6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


Take the matrix `A` and make a larger matrix by tiling the old one the number of times specified.

In [25]:
numpy.tile(A, (2,2))

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

Transpose!

In [26]:
A.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

## Mathematical Functions
Similar to the built-in Python module `math`, NumPy also provides a number of common math functions such as `sqrt`, `sin`, `cos`, and `tan` along with a number of useful constants, the most important of which is $pi$.  The benefit of using NumPy's versions is that they can be used on entire arrays.

In [28]:
x = numpy.linspace(-2.0 * numpy.pi, 2.0 * numpy.pi, 62)
y = numpy.sin(x)
print y

[  2.44929360e-16   2.04552066e-01   4.00453906e-01   5.79421098e-01
   7.33885366e-01   8.57314628e-01   9.44489229e-01   9.91722674e-01
   9.97017526e-01   9.60149874e-01   8.82678798e-01   7.67880446e-01
   6.20609482e-01   4.47093793e-01   2.54671120e-01   5.14787548e-02
  -1.53890577e-01  -3.52752087e-01  -5.36696194e-01  -6.97944155e-01
  -8.29677014e-01  -9.26323968e-01  -9.83797952e-01  -9.99668468e-01
  -9.73264374e-01  -9.05702263e-01  -7.99839245e-01  -6.60152121e-01
  -4.92548068e-01  -3.04114832e-01  -1.02820997e-01   1.02820997e-01
   3.04114832e-01   4.92548068e-01   6.60152121e-01   7.99839245e-01
   9.05702263e-01   9.73264374e-01   9.99668468e-01   9.83797952e-01
   9.26323968e-01   8.29677014e-01   6.97944155e-01   5.36696194e-01
   3.52752087e-01   1.53890577e-01  -5.14787548e-02  -2.54671120e-01
  -4.47093793e-01  -6.20609482e-01  -7.67880446e-01  -8.82678798e-01
  -9.60149874e-01  -9.97017526e-01  -9.91722674e-01  -9.44489229e-01
  -8.57314628e-01  -7.33885366e-01

This is often useful for plotting functions easily or setting up a problem (we will cover plotting later).

One thing to watch out for (and this is true of the `math` module) is that contrary to what you might expect:

In [29]:
x = numpy.linspace(-1, 1, 20)
numpy.sqrt(x)

/Users/mandli/src/envs/claw/lib/python2.7/site-packages/ipykernel/__main__.py:2: RuntimeWarning: invalid value encountered in sqrt
  from ipykernel import kernelapp as app


array([        nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
        0.22941573,  0.39735971,  0.51298918,  0.60697698,  0.6882472 ,
        0.76088591,  0.82717019,  0.88852332,  0.9459053 ,  1.        ])

The problem is that if you take the `sqrt` of a negative number NumPy does not automatically use the `Complex` variable type to represent the output.  Unlike lists, NumPy requires the data stored within to be uniform (of the same type or record structure).  By default NumPy assumes we want `float`s which obey the IEEE compliant floating point rules for arithmitec (more on this later) and generates `nan`s instead (`nan` stands for "not-a-number", see more about this special value [here]()).

If we want to deal with complex numbers there is still a way to tell NumPy that we want the `Complex` data type instead by doing the following:

In [30]:
x = numpy.linspace(-1, 1, 20, dtype=complex)
numpy.sqrt(x)

array([ 0.00000000+1.j        ,  0.00000000+0.9459053j ,
        0.00000000+0.88852332j,  0.00000000+0.82717019j,
        0.00000000+0.76088591j,  0.00000000+0.6882472j ,
        0.00000000+0.60697698j,  0.00000000+0.51298918j,
        0.00000000+0.39735971j,  0.00000000+0.22941573j,
        0.22941573+0.j        ,  0.39735971+0.j        ,
        0.51298918+0.j        ,  0.60697698+0.j        ,
        0.68824720+0.j        ,  0.76088591+0.j        ,
        0.82717019+0.j        ,  0.88852332+0.j        ,
        0.94590530+0.j        ,  1.00000000+0.j        ])

There are number of other data types that NumPy understands, the most important one being `int` for integers.